# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Письма с войны (1941)
email: andrew.bizyaev@gmail.com
description: "Письма моего деда Бизяева Ерофея Михайловича с момента призыва в РККА в августе 1941 года по декабрь 1941. Дед пропал без вести и предположительно погиб в период с декабря 1941 по март 1942 года под Москвой (Клин, Ржев) в составе 365 дивизии."
baseurl: "/letters-from-war"
url: "http://andrewbiz.github.io"
github_username: AndrewBiz
exclude: [materials]

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
